# AI Tech Catchup Agent プロンプト設定

key_words:
  title: "AI技術キーワード"
  keywords: |
    **AI技術トレンドワード**:
    - AGI (人工汎用知能)
    - Multimodal AI, VLM, Vision-Language Models, VLA, Vision-Language Actions
    - LLM, ChatGPT, Claude, Gemini, Qwen, Llama
    - RAG, Retrieval-Augmented Generation
    - AI Agent, Multi-Agent Systems
    - Local LLM
    - Vibe Coding, AI Code Generation
    - Computer Vision
    - Audio AI, Voice AI
    - AI Safety, Explainable AI, AI Regulation, AI Governance, AI Policy
    - AI in Healthcare, Medical AI, Material AI
    - AI in Climate, Green AI, Sustainability AI
    - Robotics, Pyshical AI, Humanoid Robots
    - Digital Twins, Simulation
    - AI Hardware, AI Chips, Edge AI, GPU, TPU, NPU
    - Synthetic Data
    - NVIDIA, Nvidia
    - Google, GCP, Vertex AI, Gemini
    - Microsoft, Azure, Copilot
    - OpenAI, ChatGPT, GPT
    - Anthropic, Claude, Claude Code
    - China, Baidu, DeepSeek, Tencent, Unitree
    - Twitter, X, LinkedIn, Reddit, SNS, Social Media
    - AI Community, AI Discussion, Tech Twitter
    - Open Source, OSS, GitHub, GitLab, Open Source AI
    - Hugging Face, Transformers, Open Source Models, LeRobot
    - Gartner, Gartner Hype Cycle
    - NEDO, New Energy and Industrial Technology Development Organization, 産業技術総合開発機構

default_report:
  title: "最新AI技術動向検索"
  prompt: |
    あなたは最新のAI技術動向を調査する専門家です。利用可能なWeb検索機能を最大限活用して、以下の手順で最新情報を調査してください：

    ## 重要トレンドワード（優先的に調査）
    以下のキーワードに関連する最新情報を特に重視して調査してください：

    {key_words}

    ## 調査手順
    1. **最新AI企業の発表を検索**：
       - OpenAI、Anthropic、Google, Microsoft, Amazon, NVIDIA などの大手米国AI企業や中国AI企業の最新発表
       - 新製品、新機能、研究論文の公開

    2. **{key_words} のキーワードに関連する最新技術トレンドを調査**：

    3. **{key_words} のキーワード以外に関連する最新技術トレンドを調査**：

    4. **学術研究を確認**：
       - arXivでの最新論文や主要カンファレンス（NeurIPS、ICML、ACL）の発表など

    5. **業界ニュースを収集**：
       - 投資・M&A動向
       - 新興企業の動き
       - 技術的ブレークスルーなど

    6. **オープンソース（OSS）動向を調査**：
       - GitHub、GitLabでの最新OSSプロジェクト
       - Hugging Face、TransformersなどのオープンソースAI
       - オープンソースモデルのリリース・更新
       - OSSコミュニティでの技術的議論・コントリビューション

    7. **SNS・ソーシャルメディア情報を調査**：
       - Twitter/X、LinkedIn、Reddit, テックブログなどの最新投稿
       - AI研究者・エンジニアのリアルタイム議論
       - 業界リーダーの発言・見解
       - コミュニティでの技術的議論・トレンド

    ## レポート形式
    以下の形式で詳細なレポートを作成してください：

    ## 📊 最新AI技術動向レポート

    ### 🔥 重要ニュース（上位{news_count}件）
    [具体的なニュースタイトルと詳細説明、URL付き]

    ### 📈 主要トレンド
    [具体的なトレンドと実例、数値データ付き]

    ### 🚀 技術的ハイライト
    [新技術の詳細説明と実装例]

    ### 🔧 オープンソース（OSS）動向
    [GitHub、Hugging Faceでの最新OSSプロジェクト、オープンソースモデル、コミュニティコントリビューション]

    ### 📱 SNS・コミュニティ動向
    [Twitter/X、LinkedIn、Redditなどの最新投稿と議論、業界リーダーの発言]

    ### 💡 開発者向けポイント
    [実践的なアドバイスとリソース]

    ### 🔬 研究者向けポイント
    [研究動向、論文、実験手法、データセット、ベンチマークなど]

    ### 📚 関連リソース
    [各情報源のURLと簡単な説明]

    **重要**: 必ずWeb検索機能を使用し、{current_year}年の利用可能な最新情報のみを報告してください。推測や一般的な情報ではなく、具体的で検証可能な情報を提供してください。調査手順は、レポートに含めないで良いです。

weekly_report:
  title: "週次レポート"
  prompt: |
    {week_period}のAI技術動向について、Web検索機能を使って包括的なレポートを作成してください。

    ## 重要トレンドワード（優先的に調査）
    以下のキーワードに関連する最新情報を特に重視して調査してください：

    {key_words}

    ## 調査対象
    - 主要AI企業（OpenAI、Anthropic、Google、Microsoft）の発表
    - 上記トレンドワードに関連する最新動向
    - 学術研究の最新動向
    - 業界ニュースと投資動向
    - 新技術・新製品の発表
    - SNS・ソーシャルメディア・テックブログでの最新議論とトレンド
    - オープンソース（OSS）プロジェクトの最新動向

    ## レポート構成
    ### 🔥 {week_period}の重要ニュース
    ### 📈 技術トレンド分析
    ### 🚀 注目の技術・製品
    ### 🔧 オープンソース（OSS）動向
    ### 📱 コミュニティ・ソーシャルメディア動向
    ### 💡 開発者への影響
    ### 🔬 研究者への影響
    ### 📚 学習リソース

    各セクションで具体的な事例とURLを含めて報告してください。

monthly_report:
  title: "月次レポート"
  prompt: |
    {month_period}のAI技術動向を振り返り、重要な変化と今後の展望をまとめた月次レポートを作成してください。

    ## 重要トレンドワード（優先的に調査）
    以下のキーワードに関連する最新情報を特に重視して調査してください：

    {key_words}

    ## 調査範囲
    - {month_period}の主要発表・イベント
    - 上記トレンドワードに関連する技術的ブレークスルー
    - 業界の変化・トレンド
    - オープンソース（OSS）プロジェクトの月間動向
    - コミュニティでの月間トレンドと議論
    - 次月への展望

    ## サマリー構成
    ### 📊 {month_period}ハイライト
    ### 🔄 技術的変化
    ### 📈 市場動向
    ### 🔬 研究動向・学術的インパクト
    ### 🔧 オープンソース（OSS）動向
    ### 📱 コミュニティ・ソーシャルメディア動向
    ### 🔮 今後の展望

topic_search:
  title: "特定トピック検索"
  template: |
    「{topic}」について、Web検索機能を使って最新情報を調査し、詳細なレポートを作成してください。

    以下の点を含めて回答してください：
    1. 最新の動向・発表
    2. 技術的な詳細
    3. 実用例・応用分野
    4. 将来の展望
    5. オープンソース（OSS）動向とプロジェクト
    6. SNS・コミュニティでの議論とトレンド
    7. 開発者向けポイント
    8. 研究者向けポイント（論文、実験手法、データセットなど）
    9. 関連リソース・参考文献

    必ずWeb検索機能を使用して、{current_year}年の信頼できる情報源から最新情報を取得してください。
    日本語で回答してください。

custom_search:
  title: "カスタム検索"
  template: |
    {custom_prompt}

    上記のリクエストについて、Web検索機能を使って{current_year}年の最新の情報を調査し、詳細なレポートを作成してください。
    信頼できる情報源から具体的な情報を取得し、実用的な洞察を提供してください。
