name: Weekly Report

on:
  workflow_dispatch:
  schedule:
    # 毎週金曜日 9:00 (JST)
    - cron: '0 0 * * 5'

jobs:
  ai-tech-catchup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Claude Code CLI
        run: |
          npm install -g @anthropic-ai/claude-code

      - name: Install dependencies
        run: |
          uv sync --frozen

      - name: Run AI Tech Catchup Agent
        env:
          MODEL_NAME: ${{ vars.MODEL_NAME }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          make run-weekly

      - name: Create summary
        if: always()
        run: |
          echo "## AI Tech Catchup Agent Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **実行日時**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- **リポジトリ**: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "- **ワークフロー**: ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY
          echo "- **実行結果**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
